create separate component for opt popups, fix styling in new popup
Talishar/Talishar-FE pull request #288
Opened 2023-04-05 04:37 UTC by tickct

So the issue is due to us using the same form for when we need a submit button, when we have text options and when we have opt options. 

To make this fix more long term. I have broken out popups of id OPT into a new form component and created and other form component to have a fallback. Moving forward this will allow us to do different things in the popup using the ID to define the layout style for the form.

![image](https://user-images.githubusercontent.com/8871975/229982127-28a3e3eb-9089-4c31-aaa4-e55ec568f354.png)

![image](https://user-images.githubusercontent.com/8871975/229982240-2bd55545-9c68-4a45-8d44-f3ed04a6c84e.png)

Test Deck Link: https://fabrary.net/decks/01GX2F3RM59TYDSWFK1T92MFCY

2023-04-06 01:07 UTC, LaustinSpayce commented
I left some comment / change which needs to be addressed otherwise all LGTM and I can merge it after the change is done.

2023-04-06 02:48 UTC, tickct commented
I don't see any comments on this PR at the moment, happy to adjust once they are here

2023-04-06 04:41 UTC, LaustinSpayce requested changes

2023-04-06 04:42 UTC, LaustinSpayce commented
> I don't see any comments on this PR at the moment, happy to adjust once they are here

Turns out I need to start it, and then press "request changes" so you can see them, my bad.

2023-04-07 03:43 UTC, LaustinSpayce approved these changes
lgtm thanks for making the change

2023-04-07 03:43 UTC, merged